DATABASE_PATH: "data/database.sqlite3"
VEDIS_PATH: "data/export_cooldown.vedis"
LOG_FILE_PATH: "logs/latest.log"

BOT_TOKEN: ""  # https://t.me/BotFather
WEATHER_API_KEY: ""  # https://home.openweathermap.org/api_keys

BOT_NOTIFICATIONS: True  # Are notifications enabled at the bot level
POKE_SERVER_URL: False  # Should server poke the link SERVER_URL
SERVER_URL: ""
LIMIT_IMAGE_GENERATOR_URL: ""

TELEGRAM_WEBHOOK: False  # Is Telegram webhook enabled?
TELEGRAM_WEBHOOK_URL: ""  # Full Telegram webhook url
TELEGRAM_WEBHOOK_FLASK_PATH: ""  # Telegram webhook Flask path

GITHUB_WEBHOOK: False  # Is GitHub webhook enabled?
GITHUB_WEBHOOK_FLASK_PATH: ""  # GitHub webhook Flask path
GITHUB_WEBHOOK_SECRET: ""  # GitHub webhook secret
WSGI_PATH: ""  # WSGI file path. For PythonAnyWhere "/var/www/<your_username>_pythonanywhere_com_wsgi.py"

ADMIN_IDS:  # list of admins chat_id
  - admin_chat_id
