SQLALCHEMY_DATABASE_URI: {
    "master": "sqlite:///data/database.sqlite3",
}
LOG_FILE_PATH: "logs/latest.log"

BOT_TOKEN: ""  # https://t.me/BotFather
WEATHER_API_KEY: ""  # https://home.openweathermap.org/api_keys

MIN_CALENDAR_YEAR: 1900
MAX_CALENDAR_YEAR: 2300

BOT_NOTIFICATIONS: True  # Are notifications enabled at the bot level?
LIMIT_IMAGE_GENERATOR_URL: ""  # "/limit" Flask endpoint for generating pictures of limits

TELEGRAM_WEBHOOK: False  # Is Telegram webhook enabled?
TELEGRAM_WEBHOOK_URL: ""  # Full Telegram webhook url
TELEGRAM_WEBHOOK_FLASK_PATH: ""  # Telegram webhook Flask path
TELEGRAM_WEBHOOK_SECRET_TOKEN: ""  # Telegram webhook secret token 1-256 characters.
                                   # Only characters A-Z, a-z, 0-9, _ and - are allowed.

GITHUB_WEBHOOK: False  # Is GitHub webhook enabled?
GITHUB_WEBHOOK_FLASK_PATH: ""  # GitHub webhook Flask path
GITHUB_WEBHOOK_SECRET: ""  # GitHub webhook secret

WSGI_PATH: ""  # WSGI file path. For PythonAnyWhere "/var/www/<your_username>_pythonanywhere_com_wsgi.py"

ADMIN_IDS:  # list of admins chat_id
  - admin_chat_id
